// ALFRED · DISPRON — Los 12 sub-agentes (nombres propios preservados) adaptados a captación y operación comercial de DISPRON GROUP.
module.exports = [
  { id: 'thomas', name: 'Thomas', role: 'Arquitecto de Plataforma', roleEN: 'Platform Architect', category: 'Arquitectura y Diseño de Sistemas', color: '#4cc9f0',
    desc: 'Mapea la arquitectura de la plataforma DISPRON (sitio, CRM, Sofía, Alfred) y su inventario real.',
    keywords: ['arquitectura', 'diagrama', 'inventario', 'plataforma', 'componentes', 'mermaid'] },
  { id: 'ada', name: 'Ada', role: 'Ingeniera de Calidad', roleEN: 'Quality Engineer', category: 'Ingeniería y Calidad de Software', color: '#7bdff2',
    desc: 'Verifica la salud real del sitio: renderiza cada página, valida imágenes y enlaces internos.',
    keywords: ['salud', 'health', 'pruebas', 'test', 'roto', 'imagenes rotas', 'error', 'verifica el sitio'] },
  { id: 'leonardo', name: 'Leonardo', role: 'Integraciones y Datos Estructurados', roleEN: 'Integrations & Structured Data', category: 'Integración, APIs y JSON-LD', color: '#9d8cff',
    desc: 'Genera la especificación OpenAPI de la plataforma y previsualiza el JSON-LD de cada página.',
    keywords: ['openapi', 'api', 'swagger', 'json-ld', 'jsonld', 'schema', 'datos estructurados'] },
  { id: 'victoria', name: 'Victoria', role: 'Analista de Datos, SEO y GEO', roleEN: 'Data, SEO & GEO Analyst', category: 'Analítica, SEO y GEO', color: '#C5A059',
    desc: 'Reportes de pipeline y pronóstico, auditoría SEO/GEO real del sitio y plan de posicionamiento por servicio.',
    keywords: ['reporte', 'pipeline', 'metricas', 'seo', 'geo', 'posicionamiento', 'ranking', 'primer lugar', 'pronostico', 'conversion', 'analitica', 'gpt', 'llms'] },
  { id: 'marcus', name: 'Marcus', role: 'Director de Ventas y Crecimiento', roleEN: 'Sales & Growth Lead', category: 'Ventas, Prospección y Marketing', color: '#f4a261',
    desc: 'Califica leads, define la próxima mejor acción, redacta seguimientos, briefs de campaña y planes de prospección por sector.',
    keywords: ['lead', 'prospecto', 'cliente', 'ventas', 'seguimiento', 'campana', 'marketing', 'prospeccion', 'score', 'calificar', 'buscar clientes', 'proxima accion'] },
  { id: 'webb', name: 'Webb', role: 'Operaciones y Despliegue', roleEN: 'Operations & Deployment', category: 'Infraestructura y Operación', color: '#80ed99',
    desc: 'Estado del entorno, respaldos de la base y lista de verificación de despliegue.',
    keywords: ['respaldo', 'backup', 'despliegue', 'deploy', 'entorno', 'servidor', 'produccion'] },
  { id: 'grace', name: 'Grace', role: 'Atención al Cliente', roleEN: 'Customer Care', category: 'Atención y Soporte', color: '#ff8fab',
    desc: 'Tickets de soporte, búsqueda en FAQs/guías técnicas y escalamiento de casos urgentes.',
    keywords: ['ticket', 'faq', 'pregunta frecuente', 'escalar', 'reclamo', 'soporte', 'queja', 'emergencia'] },
  { id: 'fortress', name: 'Fortress', role: 'Seguridad', roleEN: 'Security', category: 'Ciberseguridad y Cumplimiento', color: '#ef476f',
    desc: 'Auditoría de seguridad de la plataforma y detección de leads sospechosos o spam.',
    keywords: ['seguridad', 'auditoria de seguridad', 'amenaza', 'spam', 'vulnerabilidad', 'riesgo', 'sospechoso'] },
  { id: 'doc', name: 'Doc', role: 'Documentación y Propuestas', roleEN: 'Documentation & Proposals', category: 'Documentación Comercial', color: '#e9ecef',
    desc: 'Genera propuestas técnico-comerciales en HTML por lead y listas de verificación para visitas técnicas.',
    keywords: ['propuesta', 'cotizacion', 'documento', 'checklist de visita', 'levantamiento', 'informe', 'visita tecnica'] },
  { id: 'sterling', name: 'Sterling', role: 'Constructor de Producto', roleEN: 'Product Builder', category: 'Lanzamiento de Producto', color: '#ffd166',
    desc: 'Checklist de lanzamiento con verificación real de datos pendientes (PENDIENTE_DE_VALIDAR).',
    keywords: ['lanzamiento', 'launch', 'pendiente', 'validar', 'publicar', 'checklist de lanzamiento'] },
  { id: 'minerva', name: 'Minerva', role: 'Memoria y Contexto', roleEN: 'Memory & Context', category: 'Memoria y Contexto', color: '#b5179e',
    desc: 'Memoria persistente: guarda hechos, los recupera y resume el historial de una oportunidad.',
    keywords: ['recuerda', 'memoria', 'guarda', 'resumen del lead', 'historial', 'que sabes', 'recuerdas'] },
  { id: 'hugo', name: 'Hugo', role: 'Comunicación Bilingüe', roleEN: 'Bilingual Communication', category: 'Comunicación ES/EN', color: '#48cae4',
    desc: 'Detecta idioma y entrega mensajes comerciales en español o inglés para clientes internacionales.',
    keywords: ['ingles', 'english', 'traduce', 'translate', 'bilingue', 'idioma', 'en ingles'] },
];
